#!/bin/bash

./disassembly champstest/Asombra.cor
./disassembly champstest/fluttershy.cor
./disassembly champstest/Kappa.cor
./disassembly champstest/gedeon.cor
./disassembly champstest/Machine-gun.cor
./disassembly champstest/helltrain.cor
./disassembly champstest/MarineKing.cor
./disassembly champstest/jinx.cor
./disassembly champstest/Misaka_Mikoto.cor
./disassembly champstest/justin_bee.cor
./disassembly champstest/Rainbow_dash.cor
./disassembly champstest/littlepuppy.cor
./disassembly champstest/THUNDER.cor
./disassembly champstest/live.cor
./disassembly champstest/Varimathras.cor
./disassembly champstest/loose.cor
./disassembly champstest/Wall.cor
./disassembly champstest/mandragore.cor
./disassembly champstest/_.cor
./disassembly champstest/meowluigi.cor
./disassembly champstest/_honeybadger.cor
./disassembly champstest/salamahenagalabadoun.cor
./disassembly champstest/bee_gees.cor
./disassembly champstest/sam_2.0.cor
./disassembly champstest/big_feet.cor
./disassembly champstest/seg.cor
./disassembly champstest/big_life.cor
./disassembly champstest/skynet.cor
./disassembly champstest/bigzork.cor
./disassembly champstest/terminator.cor
./disassembly champstest/casimir.cor
./disassembly champstest/test.cor
./disassembly champstest/champ.cor
./disassembly champstest/turtle.cor
./disassembly champstest/corelol.cor
./disassembly champstest/ultimate-surrender.cor
./disassembly champstest/darksasuke.cor
./disassembly champstest/while_fork.cor
./disassembly champstest/doge.cor
./disassembly champstest/youforkmytralala.cor
./disassembly champstest/dubo.cor
./disassembly champstest/zork.cor
./disassembly champstest/fat_42.cor
